---
galaxy_info:
  role_name: xrdp
  namespace: lit
  author: Lightning IT
  description: Install and configure XRDP on Ubuntu. Does not enable repos; use lit.ubuntu.repos.
  company: Lightning IT
  license: GPL-3.0-only
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions: ["jammy", "noble"]
  galaxy_tags:
    - ubuntu
    - rdp
    - xrdp
dependencies: []
