---
galaxy_info:
  role_name: hostname
  namespace: lit
  author: Rene Osorio
  description: Set the system hostname and manage an /etc/hosts entry.
  company: Lightning IT
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble

  galaxy_tags:
    - modulix
    - ubuntu
    - hostname
    - networking
    - system
    - automation

dependencies: []
