---
galaxy_info:
  role_name: incus
  namespace: lit
  author: Rene Osorio
  description: Install and initialize Incus on Ubuntu hosts.
  company: Lightning IT
  license: GPL-3.0-only
  min_ansible_version: "2.15"

  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble

  galaxy_tags:
    - incus
    - ubuntu
    - virtualization
    - containers
    - qemu

dependencies: []
