---
galaxy_info:
  role_name: incus
  namespace: lit
  author: Rene Osorio
  description: Configure Ubuntu hosts as Incus hosts for containers and VMs.
  company: Lightning IT
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble

  galaxy_tags:
    - incus
    - ubuntu
    - virtualization
    - containers
    - qemu

dependencies: []
