---
- name: Verify firefox destroy syntax coverage
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Check lit.ubuntu.firefox_destroy coverage marker
      ansible.builtin.stat:
        path: "{{ lookup('ansible.builtin.env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/firefox_destroy-syntax-coverage"
      register: firefox_destroy_molecule_coverage_marker

    - name: Assert lit.ubuntu.firefox_destroy coverage stub ran
      ansible.builtin.assert:
        that:
          - firefox_destroy_molecule_coverage_marker.stat.exists
        quiet: true
