---
namespace: lit
name: ubuntu
version: 0.1.0
readme: README.md
description: Ubuntu-focused collection for OS baseline, hardening, user/package management,
  and day-2 operational tasks.
repository: https://github.com/lightning-it/ansible-collection-ubuntu
authors:
  - Lightning IT
license:
  - GPL-3.0-only
tags:
  - modulix
  - ubuntu
  - linux
  - hardening
  - baseline
  - security
  - compliance
  - automation
dependencies:
  ansible.posix: '*'
  community.general: '>=11.4.5,<12.0.0'
  community.docker: '*'
build_ignore:
  - node_modules
  - collections
  - vagrant
  - .git
  - .github
  - .gitignore
  - .molecule
  - ansible_collections
  - infra
  - '*.terraform*'
  - '*.tar.gz'
