---
driver:
  name: docker

dependency:
  name: galaxy
  options:
    requirements-file: "${MOLECULE_PROJECT_DIRECTORY}/collections/requirements.yml"

platforms:
  - name: incus
    image: ubuntu:24.04
    pre_build_image: true
    command: sleep infinity
    network_mode: host

provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
          incus:
            ansible_connection: docker
  playbooks:
    converge: converge.yml
    verify: verify.yml

verifier:
  name: ansible
