---
- name: Verify firefox syntax coverage
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Check lit.ubuntu.firefox coverage marker
      ansible.builtin.stat:
        path: "{{ lookup('ansible.builtin.env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/firefox-syntax-coverage"
      register: firefox_molecule_coverage_marker

    - name: Assert lit.ubuntu.firefox coverage stub ran
      ansible.builtin.assert:
        that:
          - firefox_molecule_coverage_marker.stat.exists
        quiet: true
