---
- name: Restart Incus after subordinate ID changes
  ansible.builtin.systemd_service:
    name: incus.service
    state: restarted
  listen: Restart Incus after subordinate ID changes
  when: incus_services | length > 0
...
