---
galaxy_info:
  author: Lightning IT
  description: Install Visual Studio Code and repository state on Ubuntu.
  license: MIT
  min_ansible_version: "2.18"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
dependencies: []
