---
- name: Verify firefox config syntax coverage
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Check lit.ubuntu.firefox_config coverage marker
      ansible.builtin.stat:
        path: "{{ lookup('ansible.builtin.env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/firefox_config-syntax-coverage"
      register: firefox_config_molecule_coverage_marker

    - name: Assert lit.ubuntu.firefox_config coverage stub ran
      ansible.builtin.assert:
        that:
          - firefox_config_molecule_coverage_marker.stat.exists
        quiet: true
