---
dependency:
  name: shell
  command: ":"

driver:
  name: docker

platforms:
  - name: users
    image: ubuntu:24.04
    pre_build_image: true
    command: sleep infinity
    network_mode: host

provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
          users:
            ansible_connection: docker
  playbooks:
    converge: converge.yml
    verify: verify.yml

scenario:
  name: users-basic
  test_sequence:
    - dependency
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy

verifier:
  name: ansible
