---
- name: Prechecks
  ansible.builtin.import_tasks: assert.yml
  tags: always

- name: Skip when disabled
  ansible.builtin.meta: end_host
  when: not (github_runner_enabled | bool)

- name: Ensure GitHub runner packages are installed
  ansible.builtin.apt:
    name: "{{ github_runner_packages }}"
    state: present
    update_cache: "{{ github_runner_update_apt_cache | bool }}"

- name: Ensure GitHub runner group exists
  ansible.builtin.group:
    name: "{{ github_runner_group }}"
    state: present

- name: Ensure GitHub runner user exists
  ansible.builtin.user:
    name: "{{ github_runner_user }}"
    group: "{{ github_runner_group }}"
    groups: "{{ github_runner_user_groups_extra }}"
    append: true
    home: "{{ github_runner_home }}"
    shell: /bin/bash
    create_home: true
    state: present

- name: Download GitHub runner archive
  ansible.builtin.get_url:
    url: "{{ github_runner_archive_url }}"
    dest: "{{ github_runner_archive_path }}"
    owner: root
    group: root
    mode: "0644"
  when: github_runner_instances | selectattr('state', 'undefined') | list | length > 0
    or github_runner_instances | selectattr('state', 'equalto', 'present') | list | length > 0

- name: Manage GitHub runner instances
  ansible.builtin.include_tasks: manage_instance.yml
  loop: "{{ github_runner_instances }}"
  loop_control:
    loop_var: github_runner_instance
    label: "{{ github_runner_instance.name }}"
