---
galaxy_info:
  role_name: baseline
  namespace: lit
  author: Lightning IT
  description: Install baseline packages and configure timezone and locale.
  company: Lightning IT
  license: GPL-3.0-only
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions: ["jammy", "noble"]
  galaxy_tags:
    - ubuntu
    - baseline
    - packages
    - timezone
    - locale
dependencies: []
