---
galaxy_info:
  role_name: automatic_updates
  namespace: lit
  author: René Osorio
  description: Configure weekly automatic OS updates via cron for Ubuntu systems.
  company: Lightning IT
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble

  galaxy_tags:
    - modulix
    - ubuntu
    - updates
    - security
    - cron
    - automation

dependencies: []
