---
netplan_enabled: true

netplan_config_path: /etc/netplan/99-z-lit-network.yaml
netplan_config_mode: "0600"
netplan_renderer: networkd

netplan_net_ifaces: "{{ net_ifaces | default([]) }}"
netplan_dns_servers: "{{ dns_servers | default([]) }}"
netplan_ethernets: {}
netplan_config_files_absent: []
netplan_runtime_networkd_files_absent: []

netplan_validate: true
netplan_apply: true
netplan_apply_always: false

netplan_generate_command:
  - netplan
  - generate

netplan_apply_command:
  - netplan
  - apply
