---
dependency:
  name: shell
  command: ":"

driver:
  name: default

platforms:
  - name: localhost
    managed: false

provisioner:
  name: ansible
  inventory:
    host_vars:
      localhost:
        ansible_connection: local
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml

scenario:
  name: forward-proxy-client-basic
  test_sequence:
    - dependency
    - syntax
    - prepare
    - check
    - converge
    - idempotence
    - verify

verifier:
  name: ansible
