---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: tang_deploy
    image: ubuntu:24.04
    pre_build_image: true
    command: sleep infinity
    network_mode: host
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    verify: verify.yml
  inventory:
    hosts:
      all:
        hosts:
          tang_deploy:
            ansible_connection: docker
verifier:
  name: ansible
