---
galaxy_info:
  author: Lightning IT
  description: Remove Visual Studio Code managed state on Ubuntu.
  license: MIT
  min_ansible_version: "2.18"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
dependencies: []
